# Generated by Django 2.2.2 on 2019-06-27 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo_path',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
